SELECT DISTINCT ?data ?step where {
  ?StepType rdfs:subClassOf gdprov:DataStep .
  ?step a ?StepType .
  ?DataType rdfs:subClassOf gdprov:PersonalData .
  ?data a ?DataType .
  ?step gdprov:usesData ?data .
} ORDER BY ?data